---
- name: Add key for mongodb repo without security checks.
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
  tags: install

- name: Add mongodb repo.
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install mongodb.
  apt:
    name: mongodb-org
    allow_unauthenticated: yes
    state: present
    update_cache: yes
  tags: install

- name: Enable and start mongod.
  service:
    name: mongod
    state: started
    enabled: yes
  tags: install
