---
# defaults file for app
db_host: 35.187.9.240
env: local
deploy_user: appuser
nginx_sites:
    default:
      - listen 80
      - server_name "reddit"
      - location / { proxy_pass http://127.0.0.1:9292; }
