- name: Deploy application
  hosts: app
  become: true

  tasks:
  - name: Install ruby bundler build-essential
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - ruby-full
      - ruby-bundler
      - build-essential

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/specinweb/reddit.git'
      dest: /home/appuser/reddit
      version: monolith   # <-- Указываем нужную ветку
    notify: reload puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
