- name: Deploy App
  hosts: app
  become: true

  tasks:
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/specinweb/reddit.git'
      dest: "/home/{{ deploy_user }}/reddit"
      version: monolith   # <-- Указываем нужную ветку
    notify: restart puma

  - name: Bundle install
    bundler:
      state: present
      chdir: "/home/{{ deploy_user }}/reddit" # <-- В какой директории выполнить команду bundle

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
