---
- name: Configure App
  hosts: app
  become: true 
  tags: app-tag  

  vars:
    db_host: 35.205.56.15

  tasks:
  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma

  - name: Add config for DB connection
    template:      
      src: templates/db_config.j2
      dest: /home/appuser/db_config
      owner: appuser
      group: appuser

  - name: enable puma
    systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted

- name: Deploy application
  hosts: app
  become: true
  tags: deploy-tag 

  tasks:
  - name: Install ruby bundler build-essential
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - ruby-full
      - ruby-bundler
      - build-essential

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/specinweb/reddit.git'
      dest: /home/appuser/reddit
      version: monolith   # <-- Указываем нужную ветку
    notify: reload puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted

- name: Configure MongoDB
  hosts: db 
  become: true
  tags: db-tag

  vars:
    mongo_bind_ip: 0.0.0.0 

  tasks:
  - name: Add key for mongodb repo without security checks.
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927

  - name: Add mongodb repo.
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install mongodb.
    apt:
      name: mongodb-org
      allow_unauthenticated: yes
      state: present
      update_cache: yes

  - name: Enable and start mongod.
    service:
      name: mongod
      state: started
      enabled: yes

  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod

  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted